### ISSUE TITLE
Create exchange yaml incorrect

### ISSUE THREAD

**Issue by dlongley** [w3c-ccg/vc-api#434]
The incorrect section is here:

https://github.com/w3c-ccg/vc-api/blob/5aff850700e18818cfa752c7201491c494caa56e/exchanges.yml#L313-L334

It should instead look something like this:

```
    CreateExchangeRequest:
      type: object
      description: Object containing information about the exchange to be created.
      properties:
        ttl:
          type: number
          description: Time to live for the exchange (seconds).
        variables:
          type: object
          description: Template variables to be used in the exchange.
        openId:
          type: object
          description: Optional parameters to enable OID4* protocol for delivery.
```
