### ISSUE TITLE
Unspecified enumeration of accepted values for template properties

### ISSUE THREAD

**Issue by kezike** [w3c-ccg/vc-api#449]
For `workflow.credentialTemplates` and `workflow.steps[stepName].stepTemplate`, what is the complete range of values for `type`? I am aware that `jsonata` has been used in some implementations, but I don’t see this or a comprehensive range documented anywhere in the specification. Is there a plan to specify this?

**Comment by dlongley** [comment]
@kezike,

I don't think we would specify a complete range of values for `type`, it is essentially an extension point. As you noted, implementations are already using `jsonata` as an identifier for one template type -- but others could be used as well and the spec wouldn't limit this. The spec might suggest one or more options, but recommending or requiring support for at least one template language would require a normative reference in a W3C spec; something that might not be easily done with template languages.

**Comment by kezike** [comment]
@dlongley 

OK, in that case, how do you envision that an extension would be advertised/published for VC API extensions? That's typically done through contexts, but I have not seen much on this process for VC API.

**Comment by msporny** [comment]
The group discussed this on the 2025-02-18 telecon. @dlongley noted that we might want to leave the identifier space open as an extension field for template languages, we could try to define a few: handlebars, mustache, jsonata, etc. The group didn't have a strong preference on templating language but did note that what we're looking for here is a JSON templating language.

A PR should be raised in the specification with a jsonata example, noting that jsonata is not the only option and the choice of templating languages is implementation specific.

**Comment by kezike** [comment]
This issue has been addressed in PRs I have opened in the past. You can now find two examples of `jsonata` templates in [this section](https://w3c.github.io/vcalm/#create-workflow) of the spec. Happy to close this issue on the call later today.

**Comment by kezike** [comment]
Per my last comment, I did include `jsonata` examples in an old PR, but I would suggest that we apply the same template enum for `stepTemplate` as we do for `credentialTemplates`, for the sake of consistency. For reference, this is what the relevant OAS lines look like for `credentialTemplates`:

```
credentialTemplates:
  type: array
  description: One or more templates for credential issuance. The <code>template</code> string should render to an object containing a <code>credential</code> field, which holds the credential template, and (optionally) an <code>options</code> field, which holds important credential issuing parameters (this is the format of the request body that is sent to <code>POST /credentials/issue</code>). Passing <code>credentialTemplates</code> is OPTIONAL.
  items:
    type: object
    properties:
      id:
        type: string
        description: The ID of the template.
      type:
        type: string
        description: The type of template.
        # Other options are possible
        enum:
          - "jsonata"
      template:
        type: string
        description: The template itself.
```

I will address this soon.
